### ISSUE TITLE
No markup for unsupported language

### ISSUE THREAD

**Issue by JustusAdam** [arcticicestudio/northem-atom-syntax#1] opened 2015-07-28 22:48 UTC
I was trying out this theme and opened a Haskell source file and there seems to be no markup for it. 

I have searched the source and there's at least a 'fallback.less' file specifying some markup so why is there no markup for Haskell? I know it is not a supported language but the editor is attaching the right classes to the code pieces and I am wondering why they're not getting highlighted with the fallback.

I've attached a screenshot for your convenience.

<img width="1440" alt="screen shot 2015-07-29 at 00 48 15" src="https://cloud.githubusercontent.com/assets/5824532/8945859/82bcecd6-358b-11e5-98dd-6d451a4a8937.png">

**Comment by arcticicestudio** [comment] 2015-07-29 09:02
This is not an error, but by design.
Most syntax themes define only one file including **all classes applied to all languages**. But this way, there's no kind of "color logic" caused by the different language syntax.
I want to have **one ruleset including all classes for each language to define it as explicit as possible**.

In addition to the use of my own personal color scheme, this is one of the reasons why I started to write this syntax theme. Every language gets its own file/ruleset to ensure a continuous "color logic".

I will add as much language syntax-highlighting as possible and I'm always grateful for help and advice because I do not know every programming language.
Will add Haskell support to my TODO list for the next update =)

By the way, most of my UI & Syntax themes are still in 'indev' development state (version identifier MAJOR is `0`) and there will of course be more updates, but I have not had much free time to work on them.

**Comment by arcticicestudio** [comment] 2015-08-01 09:05
@JustusAdam I'll try to patch Haskell support today, but actually can't get the [`language-haskell`](https://atom.io/packages/language-haskell) package working (no markup appearing at all :confused:). Have you tried it using the fallback.less and if so, has it worked with it?

**EDIT**: Fixed it some hours ago. The solution is too embarrasing to post it... :no_mouth:
Hint: Always make sure to work in the repo located in the atom folder to see live results :laughing:

**Comment by arcticicestudio** [comment] 2015-08-02 18:59
Please ignore the automatic issue reference, copied the wrong issue into the CHANGELOG :unamused: , but this one is also fixed in [`0.4.0`](https://github.com/arcticicestudio/northem-atom-syntax/releases/tag/v0.4.0).

**Closed as completed** 2015-08-02 19:01 UTC
Labels: improvement, language-support

**Comment by JustusAdam** [comment] 2015-08-02 20:23
Haha :smile: thanks for adding this.

**Comment by JustusAdam** [comment] 2015-08-02 20:26
Looking pretty good too.
